### ISSUE TITLE
Use -g info to project name plus `-team` rather than user or local 

### ISSUE THREAD

**Issue by lonsbio** [bionitio-team/bionitio#60] opened 2018-02-24 13:36 UTC
When the -g option is used, a github name is provided so we could update  templated links
 for  `username` with project `code-review` from
```
https://github.com/code-review-team/code-review
```
to 
```
https://github.com/username/code-review
```

**Comment by bjpop** [comment] 2018-02-25 07:34
Thanks @lonsbio.

This is a duplicate of https://github.com/bionitio-team/bionitio/issues/58

 I will close this one and add your comment

**Closed by bjpop** 2018-02-25 07:34 UTC
Labels: duplicate, enhancement
